services:
  postgres:
    image: postgres
    environment:
      - POSTGRES_PASSWORD=123456Adm!
    ports:
      - 5432:5432
    volumes:
      - /var/lib/postgresql/data
  mongodb:
    image: mongo:latest
    environment:
      - MONGO_INITDB_ROOT_USERNAME=root
      - MONGO_INITDB_ROOT_PASSWORD=123456Adm
    ports:
      - 27017:27017
    volumes:
      - /data/db
    restart: unless-stopped
  rabbitmq:
    image: rabbitmq:3-management-alpine
    ports:
      - 5672:5672
      - 15672:15672
