services:
  postgres:
    image: postgres
    environment:
      - POSTGRES_PASSWORD=123456Adm!
    ports:
      - 5432:5432
    volumes:
      - ./docker/pg_data:/var/lib/postgresql/data
  mongodb:
    image: mongo:latest
    environment:
      - MONGO_INITDB_ROOT_USERNAME=root
      - MONGO_INITDB_ROOT_PASSWORD=123456Adm
    ports:
      - 27017:27017
    volumes:
      - ./docker/mongo_data:/data/db
    restart: unless-stopped
